version: 2
sources:
  - name: chicago
    database: dev
    schema: chicago
    tables:
      - name: chicago_311_data
        columns:
          - name: sr_number
            data_type: character varying(1024)
          - name: sr_type
            data_type: character varying(1024)
          - name: sr_short_code
            data_type: character varying(1024)
          - name: created_department
            data_type: character varying(1024)
          - name: owner_department
            data_type: character varying(1024)
          - name: status
            data_type: character varying(1024)
          - name: origin
            data_type: character varying(1024)
          - name: created_date
            data_type: character varying(1024)
          - name: last_modified_date
            data_type: character varying(1024)
          - name: closed_date
            data_type: character varying(1024)
          - name: street_address
            data_type: character varying(1024)
          - name: city
            data_type: character varying(1024)
          - name: state
            data_type: character varying(1024)
          - name: zip_code
            data_type: double precision
          - name: street_number
            data_type: character varying(1024)
          - name: street_direction
            data_type: character varying(1024)
          - name: street_name
            data_type: character varying(1024)
          - name: street_type
            data_type: character varying(1024)
          - name: duplicate
            data_type: boolean
          - name: legacy_record
            data_type: boolean
          - name: legacy_sr_number
            data_type: character varying(1024)
          - name: parent_sr_number
            data_type: character varying(1024)
          - name: community_area
            data_type: double precision
          - name: ward
            data_type: double precision
          - name: electrical_district
            data_type: double precision
          - name: electricity_grid
            data_type: character varying(1024)
          - name: police_sector
            data_type: double precision
          - name: police_district
            data_type: double precision
          - name: police_beat
            data_type: double precision
          - name: precinct
            data_type: double precision
          - name: sanitation_division_days
            data_type: character varying(1024)
          - name: created_hour
            data_type: integer
          - name: created_day_of_week
            data_type: integer
          - name: created_month
            data_type: integer
          - name: x_coordinate
            data_type: double precision
          - name: y_coordinate
            data_type: double precision
          - name: latitude
            data_type: double precision
          - name: longitude
            data_type: double precision
          - name: location
            data_type: character varying(1024)
